version: '3'

services:
####################### SERVIDOR LIGHTSTREAMER ########################
  server-ls:
  # Definir nombre del contenedor
    container_name: server-ls
  # Se va a construir a partir del fichero /Dockerfile_LS/Dockerfile
    build:
      context: ./Dockerfile_LS
      dockerfile: Dockerfile
  
  # Se redirige el puerto 8080 del contenedor al puerto 8080 de
  # localhost (para ver la página de Lightstreamer)
    ports:
      - "8080:8080"
  # En caso de error se reinicia el contenedor
    restart: on-failure
  
############################# SESIÓN -LS ##############################
  sesion-ls:
    # Definir nombre del contenedor
    container_name: sesion-ls
    # Se va a construir a partir del fichero /Dockerfile_sesion/-
    #Dockerfile
    build:
      context: ./Dockerfile_sesion
      dockerfile: Dockerfile
   
   # Define que el contenedor "server-ls" se tiene que ejecutar antes
   # (si no no puede crear una sesión)
    depends_on:
      - server-ls
   # En caso de error se reinicia el contenedor  
    restart: on-failure
   # Hace uso de un volumen al que se accede mediante /data 
    volumes:
      - infoSesion:/data

  
############################# CLIENTE -LS #############################
  cliente-ls:
    # Definir nombre del contenedor
    container_name: cliente-ls
    # Se va a construir a partir del fichero /Dockerfile_cliente/-
    # Dockerfile
    build:
      context: ./Dockerfile_cliente
      dockerfile: Dockerfile
  
    # Define que el contenedor "sesion-ls" se tiene que ejecutar antes
    # (si no, no tiene el ID de sesión para enviar los mensajes) 
    depends_on:
      - sesion-ls
   # En caso de error se reinicia el contenedor 
    restart: on-failure
   # Hace uso de un volumen al que se accede mediante /data
    volumes:
      - infoSesion:/data

###################### CONF. GENERALES ##########################

# Se detalla la configuración del volumen utilizado:
#	* nombre :  infoSesion
volumes:
  infoSesion:
  
