###################################
#       DEPLOYMENT server-ls      #
###################################

apiVersion: apps/v1
kind: Deployment

metadata:
  # Nombre del objeto deployment
  name: deployment-server-ls

# Especificaciones del objeto deployment
spec:
  # Número de pods idénticos
  replicas: 1
  selector:
    matchLabels:
      # Etiqueta para identificar el objeto
      modulo: server
      
# Plantilla a seguir para crear los Pods
  template:
    metadata:
      labels:
        # Etiqueta para identificar el objeto
        modulo: server
    # Especificaciones del contenedor que ejecutará el pod
    spec:
      containers:
      # Nombre del pod
      - name: pod-server-ls
        # Imagen base para crear el contenedor
        image: maiteupv/server-ls
        # Exponer el puerto 8080
        ports:
        - containerPort: 8080
