##################################################
#   RECLAMACIÓN VOLUMEN PERSISTENTE sesion-ls    #
##################################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rvp-sesion-ls
spec:
  accessModes:
    - ReadWriteMany
   resources:
     requests:
       storage: 2Gi 
