###################################
#       DEPLOYMENT sesion-ls      #
###################################

apiVersion: apps/v1
kind: Deployment

metadata:
  # Etiqueta para identificar el objeto
  labels:
    modulo: sesion-ls
  # Nombre del objeto deployment
  name: sesion-ls

# Especificaciones del objeto deployment
spec:
  # Número de pods idénticos
  replicas: 1
  selector:
    matchLabels:
      # Etiqueta para identificar el objeto
      modulo: sesion-ls
  
  # Plantilla a seguir para crear los Pods
  template:
    metadata:
      labels:
        # Etiqueta para identificar el objeto
        modulo: sesion-ls
    # Especificaciones del contenedor que ejecutará el pod
    spec:
      containers:
      # Imagen base para crear el contenedor
        - image: maiteupv/sesion-ls
        # Nombre del pod
          name: sesion-ls

         # Definir el punto de montaje del volumen
          volumeMounts:
            # Punto de montaje en el contenedor
            - mountPath: /data
            # Nombre del volumen
              name: infosesion
      # Politica de reinicio: Siempre
      restartPolicy: Always
      # Definir el uso de un volumen persistente 
      volumes:
      # Nombre del volumen
        - name: infosesion
          persistentVolumeClaim:
          # Debe coincidir con el nombre asignado en el 
          # fichero de reclamación del volumen persistente
            claimName: infosesion
